#!/bin/bash
#
# This script locks and removes the root account's password (if one is set). This
# prevents users from successfully logging into the root account via su. Note that it
# doesn't prevent users from becoming root via methods such as sudo su.
#
# Version: v1.0.6
# License: MIT License
#          Copyright (c) 2020-2024 Hunter T. (StrangeRanger)
#
########################################################################################
####[ Script Wide Variables ]###########################################################


green="$(printf '\033[0;32m')"
red="$(printf '\033[1;31m')"
nc="$(printf '\033[0m')"


####[ Prepping ]########################################################################


## Check if this script was executed with root privilege.
if [[ $EUID != 0 ]]; then
    echo "${red}Please run this script as or with root privilege${nc}" >&2
    echo -e "\nExiting..."
    exit 1
fi


####[ Main ]############################################################################


read -rp "We will now disable the root account. Press [Enter] to continue."

echo "Disabling root account..."
passwd -dl root || {
    echo -e "\n${red}Failed to lock the root account${nc}"
    echo -e "\nExiting..."
    exit 1
}

echo -e "\n${green}The root account has been locked${nc}"
