blank_issues_enabled: false
contact_links:
  - name: Script documentation
    url: https://github.com/StrangeRanger/linux-security-scripts#tools-and-scripts
    about: Review requirements, usage, and compatibility for each script.
