#!/bin/bash
#
# This script downloads a security auditing tool called Lynis, designed to scan a system
# and identify security issues, and provides recommendations on how to better secure it.
# Lynis, unless an error is encountered, will always be downloaded to the user's root
# directory (/home/USERNAME/).
#
# Version: v1.0.6
# License: MIT License
#          Copyright (c) 2020-2024 Hunter T. (StrangeRanger)
#
########################################################################################
####[ Script Wide Variables ]###########################################################


green="$(printf '\033[0;32m')"
cyan="$(printf '\033[0;36m')"
red="$(printf '\033[1;31m')"
nc="$(printf '\033[0m')"


####[ Prepping ]########################################################################


## Check if the script was executed with root privilege.
if [[ $EUID != 0 ]]; then
    echo "${red}Please run this script as or with root privilege${nc}" >&2
    echo -e "\nExiting..."
    exit 1
fi


####[ Main ]############################################################################


read -rp "We will now download lynis. Press [Enter] to continue."

echo "Changing working directory to '/home/$SUDO_USER'..."
cd /home/"$SUDO_USER" || {
    echo "${red}Failed to change working directory to '/home/$SUDO_USER'"
    echo "${cyan}Lynis will download to '$PWD'${nc}"
}

echo "Downloading lynis..."
git clone https://github.com/CISOfy/lynis || {
    echo "${red}Failed to download lynis${nc}" >&2
    echo -e "\nExiting..."
    exit 1
}
echo "Changing ownership of lynis to root:root..."
chown -R root:root lynis

echo -e "\n${green}Lynis has been downloaded to your system"
echo -e "${cyan}To perform a system scan with lynis, execute the following command in" \
    "the lynis root directory: sudo ./lynis audit system${nc}"
